spring:

  profiles:
    active: developer

  application:
    name: wallet

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        default_schema: money
    hibernate:
      ddl-auto: none

  jackson:
    time-zone: Europe/Moscow

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB



server:
  port: 27701
  address: 0.0.0.0

