spring:

  profiles:
    active: developer

  application:
    name: wallet

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        default_schema: money
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: true
    default-schema: money

  jackson:
    time-zone: Europe/Moscow



server:
  port: 18092
  address: 0.0.0.0

